### PR TITLE
Fix use of template0 and template1 with postgres.

### PR DESCRIPTION
**Pull request by funkybob**
template1 is the default template for creating a database with Postgres.
Also, tasks should connect to 'postgres' when issuing commands like CREATE DATABASE, not template1.

### CODE REVIEW

**Comment by kvesteri** [comment]
Is there a reason why this PR needs to modify MANIFEST.in?

**Comment by funkybob** [comment]
Sorry, no.. was trying to fix some issues we were seeing with packaging, since we're using this branch until the PR is merged.

Am happy to undo that if you'd prefer.

**Comment by funkybob** [comment]
Bump

**Comment by kvesteri** [comment]
Merged manually, thanks for the PR! :train:

**Pull request closed without merging**
