### PR TITLE
Add support for MSSQL when creating/dropping db

### PR DESCRIPTION
**Pull request by jomasti**

### CODE REVIEW

**Comment by jomasti** [comment]
I tested this locally using a SQL Server instance in Docker. I guess the same would need to be done in Travis to support running tests against SQL Server.

**Comment by deterralba** [comment]
I wanted to ask if we the support for sql server would be welcome for the create/drop operation, I am glad to see it's an ongoing work!

The value of `engine.url.database` is None when we use exact pyobdc strings (see http://docs.sqlalchemy.org/en/latest/dialects/mssql.html#pass-through-exact-pyodbc-string), hence the database creation fails.
Should this be patched here or should I create an issue the sqlalchemy repo?

**Comment by kvesteri** [comment]
Thanks for the PR. In order for this to get merged the travis CI must be configured to support MSSQL as well.

**Comment by jomasti** [comment]
@kvesteri Travis is set up with SQL Server now.

**Comment by kvesteri** [comment]
Thanks for the PR! :train:

**Pull request merged**
