### PR TITLE
#127 Added class DateTimeRangeType(RangeType):

### PR DESCRIPTION
**Pull request by ataz**
First pull request for this project. Couldn't find a dev guide on what you want in each pull request, so please let me know what else needs to be fixed before this can be merged.

### CODE REVIEW

**Comment by ataz** [comment]
I see that the commit message somehow got messed up. Was supposed to be 
"#127 Added DateTimeTZRangeType (TSTZRANGE)"

**Comment by kvesteri** [comment]
Before merging this needs:
- tests
- some mention in the docs
- commit message needs to be changed (you can use ```git commit --amend``` for example)

**Comment by ataz** [comment]
Is there any type of developers guide for this?

Which test runner do you use?

**Comment by kvesteri** [comment]
Unfortunately there is no developer guide at the moment. The code should be pep8 compliant and all new features should have unit tests and docs. The tests use pytest.

**Comment by ataz** [comment]
I'm having some trouble running the test... I keep running into new errors when trying to run them, so I'm probably doing something wrong from the onset. Could you write a quick howto with requirements and what to do to run the tests?

**Comment by kvesteri** [comment]
Just install the requirements using setup.py (see setuptools docs) and then run the tests using py.test:
```
$ py.test tests/
```

**Comment by dargueta-work** [comment]
Can we please merge this? It's pretty useful.

**Comment by kvesteri** [comment]
This still needs unit tests. Only PRs with unit tests get merged.

**Comment by kurtmckee** [comment]
It appears that this PR is stale. In addition, sqlalchemy-utils appears to support a `DateTimeRangeType` now.

I recommend closing this PR.

**Pull request closed without merging**
