### PR TITLE
json: use dialect (de)serializer to encode JSON data

### PR DESCRIPTION
**Pull request by jd**

### CODE REVIEW

**Comment by kvesteri** [comment]
Thanks for the PR. As with other PRs before merging this needs unit tests.

**Comment by jd** [comment]
@kvesteri completely agree. In this case, this would require to change `connect()` in fixture to pass a custom JSON serializer AFAIU. Would it be acceptable?

**Comment by kvesteri** [comment]
No need for that. You can just override the connection fixture on that test file / class.

**Comment by kvesteri** [comment]
JSONType will be deprecated now that SQLAlchemy has its own generic JSON type. Thus I'm closing this PR and all other JSONType related PRs

**Pull request closed without merging**
