### PR TITLE
Make comparisons with arrow type printable when literal

### PR DESCRIPTION
**Pull request by jmagnusson**
Useful when you want to see the parameters inline with the query.

### CODE REVIEW

**Comment by jmagnusson** [comment]
This includes changes from #181 as I couldn't test without it. I will rebase once that's been merged.

**Comment by kvesteri** [comment]
Thanks for the PR! :train: Rebased and merged manually.

**Comment by jmagnusson** [comment]
Nice! Might I be so rude as to ask for a new PyPI version also? :sweat_smile:

**Comment by kvesteri** [comment]
Yeah, done! :)

**Comment by jmagnusson** [comment]
Awesome. Thanks for a great project!

**Pull request closed without merging**
