### PR TITLE
Fix restrictions for newer versions for python

### LINKED ISSUE #652: sqlalchemy-utils depends on Python 3.6
https://pypi.org/project/SQLAlchemy-Utils/: 

> Requires: Python ~=3.6 

Python3.6 was end-of-life over a year ago, and now Python 3.11 is the newest version.

Our project also includes the very popular `requests` library, which only supports Python 3.7 and up.

There is no way to override this in `poetry`, the common Python installer.

https://stackoverflow.com/questions/60567732/poetry-force-install-when-versions-are-incompatible

### LINKED ISSUE #662: Release request - Python 3.11
Would it be possible to cut a release of SQLAlchemy-Utils so that we can upgrade our applications to 3.11.1?

Thanks.

### LINKED ISSUE #663: Poetry complains about sqlalchemy-utils restriction ~=3.6
If you just change it to >=3.6 will fix.

### PR DESCRIPTION
**Pull request by staticdev**
Closes #652
Closes #662 
Closes #663

### CODE REVIEW

**Comment by barrelful** [comment]
@kvesteri this is what we need, a lot of issues complain about the same problem.

**Comment by kurtmckee** [comment]
I've released sqlalchemy-utils 0.39.0. This should include fixes for sqlalchemy 2.0 beta compatibility, as well as support for Python 3.11.

**Comment by staticdev** [comment]
@kurtmckee I just tried to install version 0.39.0 in my Py 3.11 application. I am pretty sure my PR will be needed.

```sh
poetry add sqlalchemy-utils==0.39.0                

Updating dependencies
Resolving dependencies... (0.4s)

The current project's Python requirement (>=3.9.0) is not compatible with some of the required packages Python requirement:
  - sqlalchemy-utils requires Python ~=3.6, so it will not be satisfied for Python >=4.0

Because git-portfolio depends on sqlalchemy-utils (0.39.0) which requires Python ~=3.6, version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For sqlalchemy-utils, a possible solution would be to set the `python` property to ">=3.9.0,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

**Comment by kurtmckee** [comment]
[As I responded in #663](https://github.com/kvesteri/sqlalchemy-utils/issues/663#issuecomment-1364060668), this is an issue with the `pyproject.toml` file claiming support for Python 4, which is incompatible with sqlalchemy-utils' support claims.

Please modify the `tool.poetry.dependencies.python` property in `pyproject.toml`, as indicated in the error message:

```toml
[tool.poetry.dependencies]
python = ">=3.11,<4.0"
```

This will resolve the problem.

**Comment by staticdev** [comment]
@kurtmckee it is not that simple.

There is an extensive article with ideas of why one should not limit that: https://iscinumpy.dev/post/bound-version-constraints/

**Comment by kurtmckee** [comment]
@staticdev, thanks for linking that article! That really helped clarify the thinking surrounding this. I'm on board for this, and will push a new version shortly to address this.

Thanks for your patience, and for helping me understand the need. I appreciate it! :grin:

**Review by kurtmckee — APPROVED** [review]

**Pull request merged**
