### PR TITLE
Add support for built-in enum or backported enum34.

### PR DESCRIPTION
**Pull request by tonyseek**
Please review it. Thanks.

### CODE REVIEW

**Comment by mehcode** [comment]
I like where you're going with this @tonyseek 

However, I think that we should have only one kind of restricted multiple choice type. See: https://github.com/kvesteri/sqlalchemy-utils/blob/master/sqlalchemy_utils/types/choice.py

Perhaps `ChoiceType` could be upgraded to both use enumerations as the python representation and the database representation. See: #116

**Comment by tonyseek** [comment]
@mehcode I have tried to implement it.

**Comment by tonyseek** [comment]
@mehcode How about now?

**Comment by tonyseek** [comment]
@mehcode @kvesteri Is there something I can do? :-)

**Comment by kvesteri** [comment]
Thanks for the PR! :train: 

I added some minor style fixes. I think the database representation of ChoiceType should be kept as String / Unicode for now. We can add support for Enum later on the db side.

**Comment by tonyseek** [comment]
:smile:

**Pull request merged**
