### PR TITLE
WIP Add support for JSONB

### PR DESCRIPTION
**Pull request by MSusik**
* Replaces default JSONType implementation with JSONB.

### CODE REVIEW

**Comment by MSusik** [comment]
Is there a way to parametrize tests?

I'd like to have tests inside `JSONTestCase` run twice, for both values of `binary` in `JSONType` constructor.

**Comment by lsbardel** [comment]
Hi guys, any reason this is not getting merged?

**Comment by adamhadani** [comment]
:+1:  on merging, could really use this!

**Comment by kvesteri** [comment]
I'm struggling to find a way how to use JSON and JSONB comparators with this type (http://docs.sqlalchemy.org/en/latest/dialects/postgresql.html?highlight=jsonb#sqlalchemy.dialects.postgresql.JSONB). If we can't find a way I'd be inclined to remove the PostgreSQL dialect implementation and just stick with Unicode for all dialects. Without the comparators we lose much of the power of JSON and JSONB.

Is there a reason why you want to use JSONType over native JSONB type? I'm currently just using JSONB on all my projects (on the other hand I'm using PostgreSQL on every project).

**Comment by MSusik** [comment]
> Is there a reason why you want to use JSONType over native JSONB type? I'm currently just using JSONB on all my projects (on the other hand I'm using PostgreSQL on every project).

The case that made me write this simple PR was that the software I was developing was supposed to work with different versions of Postgre.

**Comment by kvesteri** [comment]
SQLAlchemy will have native JSON type as of 1.1. I'll deprecate and remove JSONType from SA-Utils at some point.

**Pull request closed without merging**
