### PR TITLE
Add support for JSONType in EncryptedType

### PR DESCRIPTION
**Pull request by rushilsrivastava**
PR integrates JSONType to work with EncryptedType

### CODE REVIEW

**Comment by kvesteri** [comment]
Can you also add unit tests for this?

**Comment by rushilsrivastava** [comment]
@kvesteri Happy to add some unit tests for this, can you point me in the right direction?

**Comment by rushilsrivastava** [comment]
@kvesteri I went ahead and added some test, let me know if I need to do something differently.

**Comment by rushilsrivastava** [comment]
So looks like the tests are failing, I am not quite sure why. [JSON](https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.JSON) is a supported type on SQLAlchemy.

**Comment by rushilsrivastava** [comment]
@kvesteri I have went ahead and added tests, it looks like the latest CI build is failing on a different test - not sure how to fix that

**Comment by rushilsrivastava** [comment]
Seems as if it was a linting problem after checking the logs again. Should be ready to go.

**Comment by rushilsrivastava** [comment]
@kvesteri I can't seem to figure out how to lint it using tox, if you could lint the imports this is ready. Thanks!

**Comment by kvesteri** [comment]
Merged manually :+1:

**Pull request closed without merging**
