### PR TITLE
Added support for backref tuple to auto_delete_orphans

### PR DESCRIPTION
**Pull request by vToMy**
When using `sqlalchemy.orm.backref` it returns a tuple.

### CODE REVIEW

**Comment by kvesteri** [comment]
Thanks for the PR, before merging this needs at least one unit test.

**Comment by vToMy** [comment]
Done!
I just copied the test for the regular use (made sure it failed first, and that my change made it pass).
It would have probably been better to somehow run the same test for both classes, but I'm not sure how you can do this.

**Comment by vToMy** [comment]
Hey,
Improved the test so there's no duplication.
Hopefully there's nothing to stop you from merging now :)

**Comment by kvesteri** [comment]
Thanks for the PR!

**Pull request merged**
